import { ArrowUpRight, CheckCircle2 } from "lucide-react";
import { PageContent } from "@/components/content/PageContent";
import { careerExperience, roleFocuses } from "@/data/profile-details";

const floatingWords = ["DESIGN", "MOTION", "CREATE", "BUILD", "THINK", "EXPLORE"];

export default function AboutPage() {
  return <PageContent eyebrow="ABOUT IRVIN" title="More than just design." description="I’m Irvin Jay Palacio, a multidisciplinary digital creative combining multimedia design, motion, video, UI design and front-end technology."><div className="grid gap-10 pt-10 lg:grid-cols-[minmax(0,1.15fr)_minmax(17rem,0.85fr)]"><section><div className="rounded-[2rem] border border-white/10 bg-white/[0.02] p-7 shadow-[0_24px_80px_rgba(0,0,0,0.28)]"><p className="text-[10px] font-semibold tracking-[0.24em] text-violet-200">ABOUT ME</p><p className="mt-6 text-base leading-8 text-[#D7DCE7]">My work sits between creativity and technology. I enjoy transforming ideas into visual experiences, interactive interfaces and practical digital products.</p><p className="mt-5 text-base leading-8 text-[#A7AFBF]">My background in operations and information technology also gives me a systems-oriented approach to creative work. Instead of focusing only on how something looks, I consider how users interact with it, how information flows, and how the complete experience works.</p><p className="mt-5 text-base leading-8 text-[#A7AFBF]">I continuously explore new technologies, creative tools and AI-assisted workflows to improve how I design, create and solve problems.</p><blockquote className="mt-8 border-l border-violet-300/40 pl-4 text-lg italic text-violet-100">“Different tools. Same passion — turning ideas into experiences.”</blockquote></div><div className="mt-8"><p className="text-[10px] font-semibold tracking-[0.24em] text-violet-200">PROFESSIONAL EXPERIENCE</p><div className="mt-6 space-y-8">{careerExperience.map((item) => <article key={item.role} className="border-l border-violet-300/35 pl-5"><p className="text-xs font-medium tracking-[0.1em] text-white/45">{item.period}</p><h2 className="mt-2 text-xl font-semibold text-white">{item.role}</h2><p className="mt-1 text-sm text-violet-200/75">{item.organization}</p><p className="mt-4 text-sm leading-6 text-[#A7AFBF]">{item.description}</p><ul className="mt-4 space-y-2">{item.responsibilities.map((responsibility) => <li key={responsibility} className="flex gap-2 text-sm leading-6 text-slate-300"><CheckCircle2 size={15} className="mt-1 shrink-0 text-violet-300" />{responsibility}</li>)}</ul></article>)}</div></div></section><aside className="space-y-5"><section className="rounded-[1.75rem] border border-white/10 bg-[#0F1620]/70 p-6"><div className="relative mx-auto max-w-[16rem]">
            <div className="relative aspect-[4/5] overflow-hidden rounded-[1.5rem] border border-white/10 bg-[radial-gradient(circle_at_50%_25%,rgba(168,85,247,0.26),rgba(14,165,233,0.06)_32%,transparent_68%)]">
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="flex size-24 items-center justify-center rounded-full border border-violet-300/40 bg-white/[0.04] text-lg font-semibold tracking-[0.2em] text-white/75 shadow-[0_0_40px_rgba(139,92,246,0.22)]">IP</div>
              </div>
              <div className="absolute inset-0 bg-[linear-gradient(180deg,transparent_50%,rgba(7,10,15,0.2)_80%,#070A0F_100%)]" />
            </div>
            {floatingWords.map((word, index) => <span key={word} className="pointer-events-none absolute text-[10px] font-semibold tracking-[0.22em] text-white/55" style={{ left: `${12 + (index * 14) % 60}%`, top: `${8 + (index * 18) % 52}%`, transform: `translate3d(${index % 2 === 0 ? 0 : 10}px, ${index % 3 === 0 ? 0 : 14}px, 0)`}}>{word}</span>)}
          </div><p className="mt-5 text-[10px] font-semibold tracking-[0.2em] text-violet-200">ABOUT RAPEX</p><h2 className="mt-3 text-xl font-semibold text-white">Logistics and marketplace platform</h2><p className="mt-3 text-sm leading-6 text-[#A7AFBF]">RAPEX is an ongoing personal platform project focused on merchant, rider, customer, delivery, and operational workflows. It is a space for applying interface design, business logic, documentation, and process improvement.</p><p className="mt-4 text-xs text-white/40">Founder and platform developer personal project</p></section><section className="rounded-2xl border border-white/10 bg-[#0F1620]/70 p-6"><p className="text-[10px] font-semibold tracking-[0.2em] text-violet-200">ROLE FOCUS</p><div className="mt-4 space-y-2">{roleFocuses.map((role) => <p key={role} className="border-b border-white/10 pb-2 text-sm leading-5 text-slate-300 last:border-0 last:pb-0">{role}</p>)}</div></section><section className="rounded-2xl border border-dashed border-white/10 bg-white/2 p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold tracking-[0.2em] text-violet-200">READY FOR</p><ArrowUpRight size={15} className="text-violet-300" /></div><p className="mt-3 text-sm leading-6 text-[#A7AFBF]">Remote creative roles, multimedia teams, product design work, and digital experience projects.</p></section></aside></div></PageContent>;
}
