import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { ImagePlaceholder } from "@/components/content/ImagePlaceholder";
import { PageContent } from "@/components/content/PageContent";
import { portfolioProjects } from "@/data/projects";

export default function WorkPage() {
  return <PageContent eyebrow="SELECTED WORK" title="A collection of digital experiences across design, motion, technology and visual communication." description="These are concept and personal portfolio pieces prepared to showcase how I approach product design, motion systems, branding and digital storytelling."><div className="pt-10"><div className="grid gap-6 xl:grid-cols-2">{portfolioProjects.map((project, index) => <article key={project.id} className="group overflow-hidden rounded-[1.75rem] border border-white/10 bg-[#0F1620]/75 p-4 shadow-[0_18px_50px_rgba(0,0,0,0.18)] transition duration-300 hover:-translate-y-1 hover:border-violet-300/25"><div className="mb-4 flex items-center justify-between"><p className="text-[10px] font-semibold tracking-[0.2em] text-violet-200">0{index + 1}</p><div className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-[9px] font-medium tracking-[0.16em] text-white/55">{project.year}</div></div><ImagePlaceholder title={project.title} subtitle={project.category} /><div className="mt-5"><h2 className="text-2xl font-semibold tracking-[-0.04em] text-white">{project.title}</h2><p className="mt-3 text-sm leading-6 text-[#A7AFBF]">{project.description}</p><div className="mt-4 flex flex-wrap gap-2">{project.tools.slice(0, 4).map((tool) => <span key={tool} className="rounded-full border border-white/10 bg-black/20 px-2.5 py-1 text-[10px] text-slate-300">{tool}</span>)}</div><Link href={`/work/${project.slug}`} className="mt-6 inline-flex items-center gap-2 rounded-full border border-violet-300/25 bg-violet-500/10 px-4 py-2 text-[10px] font-semibold tracking-[0.18em] text-violet-100 transition hover:border-violet-200/60 hover:bg-violet-500/15"><span>VIEW CASE STUDY</span><ArrowUpRight size={14} /></Link></div></article>)}</div></div></PageContent>;
}
